
tasks:
  - name: (Mynechat) Installing dependencies and running app
    init: |
      echo '🦄 📦 Installing all dependencies'
      yarn
    command: |
      echo '🦄 Running MyneChat application'
      yarn dev
    ## HOPR net repositories
  - name: (HOPRd) Installing hoprnet which contains the required scripts
    command: |
      echo '🟡 📦 Setting up hoprnet repository'
      wget https://github.com/hoprnet/hoprnet/archive/refs/heads/master.zip
      unzip master.zip
      cd hoprnet-master
      echo '🟡 📦 Installing hoprnet repository dependencies'
      yarn
      echo '🟡 📦 Building latest version of hoprnet monorepo'
      yarn build
      echo '🟡 Waiting for MyneChat'
      gp await-port 8080
      echo '🟡 Running HOPR nodes and topology'
      ./scripts/setup-local-cluster.sh -m "$(gp url 8080)" -i scripts/topologies/full_interconnected_cluster.sh
    openMode: split-right
  - name: (Mynechat) URLs
    command: |
      echo '🚦 Waiting on all nodes...'
      gp await-port 13301
      gp await-port 13302
      gp await-port 13303
      gp await-port 13304
      gp await-port 13305
      echo '🚦 Nodes Dashboard'
      echo -e "\n"
      echo -e "\t1️⃣  Alex"
      echo -e "\t\tMyneChat: $(gp url 8080)/?httpEndpoint=$(gp url 13301)&wsEndpoint=$(gp url 19501 | sed 's/https/wss/')&securityToken=^^LOCAL-testing-123^^"
      echo -e "\t\tRest API:\t$(gp url 13301)/api/v2/_swagger"
      echo -e "\t\tAdmin UI:\t$(gp url 19501)/"
      echo -e "\n"
      echo -e "\t2️⃣  Betty"
      echo -e "\t\tMyneChat: $(gp url 8080)/?httpEndpoint=$(gp url 13302)&wsEndpoint=$(gp url 19502 | sed 's/https/wss/')&securityToken=^^LOCAL-testing-123^^"
      echo -e "\t\tRest API:\t$(gp url 13302)/api/v2/_swagger"
      echo -e "\t\tAdmin UI:\t$(gp url 19502)/"
      echo -e "\n"
      echo -e "\t3️⃣  Chão"
      echo -e "\t\tMyneChat: $(gp url 8080)/?httpEndpoint=$(gp url 13303)&wsEndpoint=$(gp url 19503 | sed 's/https/wss/')&securityToken=^^LOCAL-testing-123^^"
      echo -e "\t\tRest API:\t$(gp url 13303)/api/v2/_swagger"
      echo -e "\t\tAdmin UI:\t$(gp url 19503)/"
      echo -e "\n"
      echo -e "\t4️⃣  Dmytro"
      echo -e "\t\tMyneChat: $(gp url 8080)/?httpEndpoint=$(gp url 13304)&wsEndpoint=$(gp url 19504 | sed 's/https/wss/')&securityToken=^^LOCAL-testing-123^^"
      echo -e "\t\tRest API:\t$(gp url 13304)/api/v2/_swagger"
      echo -e "\t\tAdmin UI:\t$(gp url 19504)/"
      echo -e "\n"
      echo -e "\t5️⃣  Zoe"
      echo -e "\t\tMyneChat: $(gp url 8080)/?httpEndpoint=$(gp url 13305)&wsEndpoint=$(gp url 19505 | sed 's/https/wss/')&securityToken=^^LOCAL-testing-123^^"
      echo -e "\t\tRest API:\t$(gp url 13305)/api/v2/_swagger"
      echo -e "\t\tAdmin UI:\t$(gp url 19505)/"
    openMode: tab-after

ports:
  - name: Mynechat
    port: 8080
    visibility: public
  - name: HOPRd REST API
    port: 13301-13305
    visibility: public
  - name: HOPR protocol
    port: 19091-19095
    visibility: public
  - name: HOPRd Admin
    port: 19501-19505
    visibility: public